apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    app: {{ include "helm.fullname" . }}
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: http
  selector:
    app: {{ include "helm.fullname" . }}
  type: ClusterIP
